<a href="https://colab.research.google.com/github/henselwilson/GuviTask/blob/main/Numpy_tasks_Wilson.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy



#### 1. Import the numpy package under the name `np` (★☆☆) 
(**hint**: import … as …)

In [3]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆) 
(**hint**: np.\_\_version\_\_, np.show\_config)

In [4]:
print(np.__version__)
print(np.show_config())

1.21.6
blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
blas_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
lapack_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
Supported SIMD extensions in this NumPy install:
    baseline = SSE,SSE2,SSE3
    found = SSS

#### 3. Create a null vector of size 10 (★☆☆) 
(**hint**: np.zeros)

In [5]:
a=np.zeros(10)
a

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### 4.  How to find the memory size of any array (★☆☆) 
(**hint**: size, itemsize)

In [6]:
a.size

10

#### 5.  How to get the documentation of the numpy add function from the command line? (★☆☆) 
(**hint**: np.info)

In [7]:
np.info('add')

     *** Found in numpy ***
add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is creat

#### 6.  Create a null vector of size 10 but the fifth value which is 1 (★☆☆) 
(**hint**: array\[4\])

In [8]:
arr=np.zeros(10)
arr[4]=1
arr

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

#### 7.  Create a vector with values ranging from 10 to 49 (★☆☆) 
(**hint**: np.arange)

In [9]:
b=np.arange(10,49)
b

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48])

#### 8.  Reverse a vector (first element becomes last) (★☆☆) 
(**hint**: array\[::-1\])

In [10]:
b[::-1]

array([48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33, 32,
       31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15,
       14, 13, 12, 11, 10])

#### 9.  Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆) 
(**hint**: reshape)

In [11]:
np.arange(0,9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 10. Find indices of non-zero elements from \[1,2,0,0,4,0\] (★☆☆) 
(**hint**: np.nonzero)

In [12]:
np.nonzero([1,2,0,0,4,0])

(array([0, 1, 4]),)

#### 11. Create a 3x3 identity matrix (★☆☆) 
(**hint**: np.eye)

In [13]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 12. Create a 3x3x3 array with random values (★☆☆) 
(**hint**: np.random.random)

In [14]:
from numpy import random
random.rand(3,3,3)

array([[[0.42184934, 0.30022127, 0.13919308],
        [0.06679482, 0.44220093, 0.25377645],
        [0.77479692, 0.89393426, 0.24696336]],

       [[0.04116032, 0.94658448, 0.36033077],
        [0.56345136, 0.76437012, 0.15779279],
        [0.62979499, 0.70198125, 0.78996453]],

       [[0.05770235, 0.89542169, 0.3198831 ],
        [0.53955531, 0.46932517, 0.7827436 ],
        [0.34366293, 0.41036207, 0.80592221]]])

#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆) 
(**hint**: min, max)

In [15]:
random.seed(1)
arr=random.rand(10,10)
print(arr.max())
print(arr.min())

0.9888610889064947
0.00011437481734488664


#### 14. Create a random vector of size 30 and find the mean value (★☆☆) 
(**hint**: mean)

In [16]:
random.seed(1)
arr=random.rand(30,1)
arr.mean()

0.43544785374154765

#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆) 
(**hint**: array\[1:-1, 1:-1\])

In [17]:
arz=np.ones((4,4))
arz[1:-1,1:-1]=0
arz

array([[1., 1., 1., 1.],
       [1., 0., 0., 1.],
       [1., 0., 0., 1.],
       [1., 1., 1., 1.]])

#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆) 
(**hint**: np.pad)

In [18]:
random.seed(4)
arp=random.randint(1,100,(4,4))
print(np.pad(arp,pad_width=1,mode='constant',constant_values=6))

[[ 6  6  6  6  6  6]
 [ 6 47 56 70  2  6]
 [ 6 88 73 51 10  6]
 [ 6 59 95 56 56  6]
 [ 6 58 37 51 45  6]
 [ 6  6  6  6  6  6]]


#### 17. What is the result of the following expression? (★☆☆) 
(**hint**: NaN = not a number, inf = infinity)

```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
0.3 == 3 * 0.1
```

In [19]:
nan
False
False
nan
False

NameError: ignored

#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆) 
(**hint**: np.diag)

In [20]:
np.diag(np.arange(1,5),k=-1)

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆) 
(**hint**: array\[::2\])

In [21]:
arc=np.ones((8,8))
arc[::2,::2]=0
arc[1::2,1::2]=0
arc

array([[0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.]])

#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? 
(**hint**: np.unravel_index)

In [22]:
np.unravel_index(100,(6,7,8))

(1, 5, 4)

#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆) 
(**hint**: np.tile)

In [23]:
art=np.diag(np.ones(2))
np.tile(art,(4,4))

array([[1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.]])

#### 22. Normalize a 5x5 random matrix (★☆☆) 
(**hint**: (x - min) / (max - min))

In [24]:
#Correction Normalization --> (x-mean)/(max-min)
random.seed(33)
arn=random.rand(5,5).round(2)
arn=(arn-np.min(arn)/(np.max(arn)-np.min(arn)))
arn

array([[ 2.29166667e-01,  4.29166667e-01,  3.89166667e-01,
         2.39166667e-01,  8.49166667e-01],
       [ 1.69166667e-01, -8.33333333e-04,  9.29166667e-01,
         6.59166667e-01,  4.69166667e-01],
       [ 9.49166667e-01,  3.69166667e-01,  5.91666667e-02,
         3.29166667e-01,  1.39166667e-01],
       [ 9.59166667e-01,  8.59166667e-01,  4.69166667e-01,
         3.79166667e-01,  4.29166667e-01],
       [ 6.99166667e-01,  2.29166667e-01,  5.99166667e-01,
         1.19166667e-01,  1.79166667e-01]])

#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆) 
(**hint**: np.dtype)

In [25]:
RGBA = np.dtype([('red',np.uint8),('green',np.uint8),('blue',np.uint8),('alpha',np.uint8)])
color = np.array((10,2,4,3),dtype = RGBA)
print(color['red'])
type(color)

10


numpy.ndarray

#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆) 
(**hint**: np.dot | @)

In [26]:
Mat1=np.random.randint(1,10,(5,3))
Mat2=np.random.randint(1,10,(3,2))
np.dot(Mat1,Mat2)

array([[ 47,  52],
       [ 88, 131],
       [ 54,  69],
       [ 86,  97],
       [ 71, 145]])

#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆) 
(**hint**: >, <=)

In [27]:
aRR=np.random.randint(1,20,15)
aRR[(aRR>=3) & (aRR<=8)]*=(-1)
aRR


array([10, 18, 12, -6, 15, 11,  1, 12,  1, 17, 10, 17, 11, -5,  9])

#### 26. What is the output of the following script? (★☆☆) 
(**hint**: np.sum)

```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [28]:
9
10

10

#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)

```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [29]:
# Z**Z is valid and gives the pow of the number to the number itself
# 2 << Z >> 2 is valid and gives 2^Z
# z <- z is valid and giveas boolean based on if that z is less than the -ve of itself
# 1j*z is valid and multiplies the complex number j with z
# z/1/1 is legal and gives float of the integer in Z
# z<z>z is invalid, throws error

#### 28. What are the result of the following expressions?

```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [30]:
# Nan
# 0
# array([-9.22337204e+18])

#### 29. How to round away from zero a float array ? (★☆☆) 
(**hint**: np.uniform, np.copysign, np.ceil, np.abs)

In [31]:
arr = np.random.random((4,4))
arr = np.round(arr,2)
arr

array([[0.4 , 0.02, 0.47, 0.89],
       [0.16, 0.84, 0.28, 0.77],
       [0.83, 0.9 , 0.97, 0.43],
       [0.69, 0.33, 0.8 , 0.43]])

#### 30. How to find common values between two arrays? (★☆☆) 
(**hint**: np.intersect1d)

In [32]:
ar1=np.arange(1,8)
ar2=np.arange(5,11)
np.intersect1d(ar1,ar2)

array([5, 6, 7])

#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆) 
(**hint**: np.seterr, np.errstate)

In [33]:
np.seterr(all='ignore')

{'divide': 'warn', 'invalid': 'warn', 'over': 'warn', 'under': 'ignore'}

#### 32. Is the following expressions true? (★☆☆) 
(**hint**: imaginary number)

```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [34]:
False

False

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆) 
(**hint**: np.datetime64, np.timedelta64)

In [35]:
import numpy as np
print(np.datetime64('today','D')-np.timedelta64(1,'D'))
print(np.datetime64('today','D'))
print(np.datetime64('today','D')+np.timedelta64(1,'D'))

2022-07-30
2022-07-31
2022-08-01


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆) 
(**hint**: np.arange(dtype=datetime64\['D'\]))

In [36]:
np.arange('2016-07', '2016-08', dtype='datetime64[D]')

array(['2016-07-01', '2016-07-02', '2016-07-03', '2016-07-04',
       '2016-07-05', '2016-07-06', '2016-07-07', '2016-07-08',
       '2016-07-09', '2016-07-10', '2016-07-11', '2016-07-12',
       '2016-07-13', '2016-07-14', '2016-07-15', '2016-07-16',
       '2016-07-17', '2016-07-18', '2016-07-19', '2016-07-20',
       '2016-07-21', '2016-07-22', '2016-07-23', '2016-07-24',
       '2016-07-25', '2016-07-26', '2016-07-27', '2016-07-28',
       '2016-07-29', '2016-07-30', '2016-07-31'], dtype='datetime64[D]')

#### 35. How to compute ((A+B)\*(-A/2)) in place (without copy)? (★★☆) 
(**hint**: np.add(out=), np.negative(out=), np.multiply(out=), np.divide(out=))

In [37]:
A = np.ones(3)*1
B = np.ones(3)*2
C = np.ones(3)*3
np.add(A,B,out=B)
np.divide(A,2,out=A)
np.negative(A,out=A)
np.dot(A,B)

-4.5

#### 36. Extract the integer part of a random array using 5 different methods (★★☆) 
(**hint**: %, np.floor, np.ceil, astype, np.trunc)

In [38]:
Z = np.random.uniform(0,10,10)
print(Z)
print (Z - Z%1)
print (np.floor(Z))
print (np.ceil(Z)-1)
print (Z.astype(int))
print(np.trunc(Z))

[5.10194394 7.63328637 1.73919153 4.52445538 8.98191366 6.89283121
 2.85970004 4.2086349  5.67920747 9.67631586]
[5. 7. 1. 4. 8. 6. 2. 4. 5. 9.]
[5. 7. 1. 4. 8. 6. 2. 4. 5. 9.]
[5. 7. 1. 4. 8. 6. 2. 4. 5. 9.]
[5 7 1 4 8 6 2 4 5 9]
[5. 7. 1. 4. 8. 6. 2. 4. 5. 9.]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆) 
(**hint**: np.arange)

In [39]:
A=np.arange(0,5)
np.tile(A,(5,1))

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆) 
(**hint**: np.fromiter)

In [40]:
def generate():
    for i in range(10):
        yield i
j = np.fromiter(generate(),dtype=float,count=-1)
print(j)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆) 
(**hint**: np.linspace)

In [41]:
np.linspace(0,1,11,endpoint=False)[1:]

array([0.09090909, 0.18181818, 0.27272727, 0.36363636, 0.45454545,
       0.54545455, 0.63636364, 0.72727273, 0.81818182, 0.90909091])

#### 40. Create a random vector of size 10 and sort it (★★☆) 
(**hint**: sort)

In [42]:
C=np.random.rand(10)
print(np.sort(C))

[0.17099072 0.23590537 0.34182884 0.36822585 0.56071049 0.56629399
 0.65331494 0.88547565 0.96387126 0.97286421]


#### 41. How to sum a small array faster than np.sum? (★★☆) 
(**hint**: np.add.reduce)

In [43]:
import functools as ft
Z = np.arange(10)
np.add.reduce(Z)

45

#### 42. Consider two random array A and B, check if they are equal (★★☆) 
(**hint**: np.allclose, np.array\_equal)

In [44]:
X = np.random.randint(0,5,10)
Y = np.random.randint(0,5,10)
equal = np.allclose(X,Y)
print(equal)

False


#### 43. Make an array immutable (read-only) (★★☆) 
(**hint**: flags.writeable)

In [45]:
X.flags.writeable = False

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆) 
(**hint**: np.sqrt, np.arctan2)

In [46]:
Cart=np.arange(0,50)
Cart=np.tile(Cart,(2,1))
PolR=np.sqrt(Cart[0]**2+Cart[1]**2)
PolT=np.arctan2(Cart[0],Cart[1])
Pol=np.concatenate([PolR,PolT])
Pol

array([ 0.        ,  1.41421356,  2.82842712,  4.24264069,  5.65685425,
        7.07106781,  8.48528137,  9.89949494, 11.3137085 , 12.72792206,
       14.14213562, 15.55634919, 16.97056275, 18.38477631, 19.79898987,
       21.21320344, 22.627417  , 24.04163056, 25.45584412, 26.87005769,
       28.28427125, 29.69848481, 31.11269837, 32.52691193, 33.9411255 ,
       35.35533906, 36.76955262, 38.18376618, 39.59797975, 41.01219331,
       42.42640687, 43.84062043, 45.254834  , 46.66904756, 48.08326112,
       49.49747468, 50.91168825, 52.32590181, 53.74011537, 55.15432893,
       56.56854249, 57.98275606, 59.39696962, 60.81118318, 62.22539674,
       63.63961031, 65.05382387, 66.46803743, 67.88225099, 69.29646456,
        0.        ,  0.78539816,  0.78539816,  0.78539816,  0.78539816,
        0.78539816,  0.78539816,  0.78539816,  0.78539816,  0.78539816,
        0.78539816,  0.78539816,  0.78539816,  0.78539816,  0.78539816,
        0.78539816,  0.78539816,  0.78539816,  0.78539816,  0.78

#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆) 
(**hint**: argmax)

In [47]:
Vec=np.random.randint(5,16,10)
print(Vec)
Vec[np.argmax(Vec)]=0
Vec

[14  8  8 12  7 12  7  7 14  5]


array([ 0,  8,  8, 12,  7, 12,  7,  7, 14,  5])

#### 46. Create a structured array with `x` and `y` coordinates covering the \[0,1\]x\[0,1\] area (★★☆) 
(**hint**: np.meshgrid)

In [48]:
x=[0,1]
y=[0,1]
Xax,Yax=np.meshgrid(x,y)
print(Xax)
print(Yax)

[[0 1]
 [0 1]]
[[0 0]
 [1 1]]


####  47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) 
(**hint**: np.subtract.outer)

In [49]:
Y = np.random.randint(0,11,10)
X = np.random.randint(11,22,10)
Y = np.tile(Y,(10,1))
X  = np.tile(X,(10,1)).T
C = 1/(X - Y)
C

array([[0.06666667, 0.11111111, 0.05555556, 0.0625    , 0.05882353,
        0.1       , 0.05555556, 0.05263158, 0.05882353, 0.1       ],
       [0.11111111, 0.33333333, 0.08333333, 0.1       , 0.09090909,
        0.25      , 0.08333333, 0.07692308, 0.09090909, 0.25      ],
       [0.125     , 0.5       , 0.09090909, 0.11111111, 0.1       ,
        0.33333333, 0.09090909, 0.08333333, 0.1       , 0.33333333],
       [0.07142857, 0.125     , 0.05882353, 0.06666667, 0.0625    ,
        0.11111111, 0.05882353, 0.05555556, 0.0625    , 0.11111111],
       [0.07692308, 0.14285714, 0.0625    , 0.07142857, 0.06666667,
        0.125     , 0.0625    , 0.05882353, 0.06666667, 0.125     ],
       [0.07142857, 0.125     , 0.05882353, 0.06666667, 0.0625    ,
        0.11111111, 0.05882353, 0.05555556, 0.0625    , 0.11111111],
       [0.07142857, 0.125     , 0.05882353, 0.06666667, 0.0625    ,
        0.11111111, 0.05882353, 0.05555556, 0.0625    , 0.11111111],
       [0.14285714, 1.        , 0.1      

#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆) 
(**hint**: np.iinfo, np.finfo, eps)

In [50]:
for dtype in [np.int8, np.int32, np.int64]:
    print(np.iinfo(dtype).min)
    print(np.iinfo(dtype).max)

print("\n**** \t ****\n")
for dtype in [np.float32, np.float64]:
    print(np.finfo(dtype).min)
    print(np.finfo(dtype).max)
    print(np.finfo(dtype).eps)

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807

**** 	 ****

-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


#### 49. How to print all the values of an array? (★★☆) 
(**hint**: np.set\_printoptions)

In [51]:
np.set_printoptions(threshold=1000)
np.arange(1,82).reshape(9,9)

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24, 25, 26, 27],
       [28, 29, 30, 31, 32, 33, 34, 35, 36],
       [37, 38, 39, 40, 41, 42, 43, 44, 45],
       [46, 47, 48, 49, 50, 51, 52, 53, 54],
       [55, 56, 57, 58, 59, 60, 61, 62, 63],
       [64, 65, 66, 67, 68, 69, 70, 71, 72],
       [73, 74, 75, 76, 77, 78, 79, 80, 81]])

#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆) 
(**hint**: argmin)

In [52]:
from numpy.lib.index_tricks import index_exp
Arra = np.random.uniform(0,10,10)
scalar = 3
arr_sub = np.abs(Arra - 3)
indx = arr_sub.argmin()
print(Arra)
print(Arra[indx])

[8.57967307 5.6279729  2.68832297 4.77688576 4.2214271  6.0800912
 7.18789459 4.6204037  3.86755485 0.53834636]
2.6883229662811834


#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆) 
(**hint**: dtype)

In [53]:
Z = np.zeros(10, [ ('position', [ ('x', float, 1),
                                  ('y', float, 1)]),
                   ('color',    [ ('r', float, 1),
                                  ('g', float, 1),
                                  ('b', float, 1)])])
print(Z)

[((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:5: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  """


#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆) 
(**hint**: np.atleast\_2d, T, np.sqrt)

In [54]:
arr = np.random.random((100,2))
X,Y = np.atleast_2d(arr[:,0],arr[:,1])
D = np.sqrt( (X-X.T)**2 + (Y-Y.T)**2)
D

array([[0.        , 0.53789156, 0.7261725 , ..., 0.24592131, 0.88819662,
        0.7127398 ],
       [0.53789156, 0.        , 0.28297837, ..., 0.29409557, 0.5580639 ,
        0.2758163 ],
       [0.7261725 , 0.28297837, 0.        , ..., 0.51396764, 0.28939728,
        0.01424678],
       ...,
       [0.24592131, 0.29409557, 0.51396764, ..., 0.        , 0.72506153,
        0.50180294],
       [0.88819662, 0.5580639 , 0.28939728, ..., 0.72506153, 0.        ,
        0.2911708 ],
       [0.7127398 , 0.2758163 , 0.01424678, ..., 0.50180294, 0.2911708 ,
        0.        ]])

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place? 
(**hint**: astype(copy=False))

In [55]:
Fl=np.ones(10,dtype=float)
Fl.astype(int)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

#### 54. How to read the following file? (★★☆) 
(**hint**: np.genfromtxt)

```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

In [56]:
from io import StringIO
Fil = StringIO("""1, 2, 3, 4, 5\n
                6,  ,  , 7, 8\n
                 ,  , 9,10,11\n""")
J = np.genfromtxt(Fil, delimiter=",", dtype=np.int)
print(J)

[[ 1  2  3  4  5]
 [ 6 -1 -1  7  8]
 [-1 -1  9 10 11]]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:5: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  """


#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆) 
(**hint**: np.ndenumerate, np.ndindex)

In [57]:
k = np.arange(9).reshape(3,3)
for inde, val in np.ndenumerate(k):
    print(inde, val)

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


#### 56. Generate a generic 2D Gaussian-like array (★★☆) 
(**hint**: np.meshgrid, np.exp)

In [58]:
import pandas as pd
sigma,myu = 1.0,0.0

X,Y  = np.meshgrid(np.linspace(-1,1,10),np.linspace(-1,1,10))
D = np.sqrt(X**2+Y**2)
G = np.exp(-(D-myu)**2/(2*sigma**2))
pd.DataFrame(G)

0         1         2         3         4         5         6  \
0  0.367879  0.448221  0.519795  0.573753  0.602798  0.602798  0.573753   
1  0.448221  0.546108  0.633313  0.699056  0.734444  0.734444  0.699056   
2  0.519795  0.633313  0.734444  0.810684  0.851723  0.851723  0.810684   
3  0.573753  0.699056  0.810684  0.894839  0.940138  0.940138  0.894839   
4  0.602798  0.734444  0.851723  0.940138  0.987730  0.987730  0.940138   
5  0.602798  0.734444  0.851723  0.940138  0.987730  0.987730  0.940138   
6  0.573753  0.699056  0.810684  0.894839  0.940138  0.940138  0.894839   
7  0.519795  0.633313  0.734444  0.810684  0.851723  0.851723  0.810684   
8  0.448221  0.546108  0.633313  0.699056  0.734444  0.734444  0.699056   
9  0.367879  0.448221  0.519795  0.573753  0.602798  0.602798  0.573753   

          7         8         9  
0  0.519795  0.448221  0.367879  
1  0.633313  0.546108  0.448221  
2  0.734444  0.633313  0.519795  
3  0.810684  0.699056  0.573753  
4  0.851723  0.734444  0.602798  
5  0.851723  0.734444  0.602798  
6  0.810684  0.699056  0.573753  
7  0.734444  0.633313  0.519795  
8  0.633313  0.546108  0.448221  
9  0.519795  0.448221  0.367879

#### 57. How to randomly place p elements in a 2D array? (★★☆) 
(**hint**: np.put, np.random.choice)

In [59]:
p=3
Z = np.zeros((10,10))
np.put(Z, np.random.choice(range(10*10), p),1)
Z

array([[0., 0., 0., 0., 1., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

#### 58. Subtract the mean of each row of a matrix (★★☆) 
(**hint**: mean(axis=,keepdims=))

In [60]:
Mat=np.arange(0,100).reshape(10,10)
print(Mat)
pd.DataFrame(Mat-np.mean(Mat,axis=1,keepdims=True))

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]


0    1    2    3    4    5    6    7    8    9
0 -4.5 -3.5 -2.5 -1.5 -0.5  0.5  1.5  2.5  3.5  4.5
1 -4.5 -3.5 -2.5 -1.5 -0.5  0.5  1.5  2.5  3.5  4.5
2 -4.5 -3.5 -2.5 -1.5 -0.5  0.5  1.5  2.5  3.5  4.5
3 -4.5 -3.5 -2.5 -1.5 -0.5  0.5  1.5  2.5  3.5  4.5
4 -4.5 -3.5 -2.5 -1.5 -0.5  0.5  1.5  2.5  3.5  4.5
5 -4.5 -3.5 -2.5 -1.5 -0.5  0.5  1.5  2.5  3.5  4.5
6 -4.5 -3.5 -2.5 -1.5 -0.5  0.5  1.5  2.5  3.5  4.5
7 -4.5 -3.5 -2.5 -1.5 -0.5  0.5  1.5  2.5  3.5  4.5
8 -4.5 -3.5 -2.5 -1.5 -0.5  0.5  1.5  2.5  3.5  4.5
9 -4.5 -3.5 -2.5 -1.5 -0.5  0.5  1.5  2.5  3.5  4.5

#### 59. How to sort an array by the nth column? (★★☆) 
(**hint**: argsort)

In [61]:
n=3
Z = np.random.randint(0,10,(5,5))
print(Z)
Z[Z[:,n].argsort()]

[[2 6 7 1 7]
 [8 9 1 1 4]
 [0 2 3 2 7]
 [0 6 9 2 6]
 [3 1 7 6 4]]


array([[2, 6, 7, 1, 7],
       [8, 9, 1, 1, 4],
       [0, 2, 3, 2, 7],
       [0, 6, 9, 2, 6],
       [3, 1, 7, 6, 4]])

#### 60. How to tell if a given 2D array has null columns? (★★☆) 
(**hint**: any, ~)

In [62]:
Z = np.random.randint(0,3,(3,10))
Z[:,1] = 0
Z = Z.astype(bool)
print(Z)
print(~Z)
(Z).any(axis = 0)

[[ True False False False  True  True  True  True  True  True]
 [ True False  True  True False False False  True False  True]
 [False False  True False False  True False False False  True]]
[[False  True  True  True False False False False False False]
 [False  True False False  True  True  True False  True False]
 [ True  True False  True  True False  True  True  True False]]


array([ True, False,  True,  True,  True,  True,  True,  True,  True,
        True])

#### 61. Find the nearest value from a given value in an array (★★☆) 
(**hint**: np.abs, argmin, flat)

In [63]:
Z=np.random.uniform(0,100,(20))
print(Z)
Val=7
dif=np.abs(Z-Val)
Z[dif.argmin()]

[88.4741774  67.30560537 37.74917366 89.5051111  36.12610687 94.7131499
 23.56751872 83.09820217 40.01576852 46.59526101 68.56278088 15.80503303
 19.86397551 55.47498231 94.6005512  18.94096732 93.38468178  7.92774847
 90.59132319 94.2814681 ]


7.927748469074913

#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆) 
(**hint**: np.nditer)

In [64]:
Aa=np.random.randint(0,5,10)
total=0
for x in np.nditer(Aa):
  print(x)
  total+=x
print(total)

2
3
1
0
1
2
1
4
1
0
15


#### 63. Create an array class that has a name attribute (★★☆) 
(**hint**: class method)

In [65]:
class NameArr:
  def __init__(self,namearr):
    self.namearr=namearr

  def __str__(self):
    return('Name')

#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★) 
(**hint**: np.bincount | np.add.at)

In [66]:
arr = np.array([2,3,4,7,9,11])
np.add.at(arr, [0,1,2,4], 1)
print(arr)

[ 3  4  5  7 10 11]


#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★) 
(**hint**: np.bincount)

In [67]:
randarr=np.random.randint(0,4,10)
binar=np.bincount(randarr)
print(randarr)
print(binar)

[1 2 3 1 2 1 3 0 2 2]
[1 3 4 2]


#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★★) 
(**hint**: np.unique)

In [72]:
w,h = 16,16
I = np.random.randint(0,2,(h,w,3)).astype(np.ubyte)
F = I[...,0]*(256*256) + I[...,1]*256 +I[...,2]
n = len(np.unique(F))
print(n)

8


#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★) 
(**hint**: sum(axis=(-2,-1)))

In [68]:
Bb=np.random.randint(0,256,(4,4,4,4))
Bb.sum(axis=(-2,-1))

array([[2416, 2178, 2238, 1515],
       [1967, 2265, 1763, 1672],
       [2050, 1787, 2158, 1894],
       [2404, 2265, 1678, 2500]])

#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★) 
(**hint**: np.bincount)

In [69]:
MainArr=np.arange(0,10)
Subset=3
MeanAr=[]
for i in range(len(MainArr)-3):
  MeanAr.append(MainArr[i:i+2].mean())
MeanAr

[0.5, 1.5, 2.5, 3.5, 4.5, 5.5, 6.5]

#### 69. How to get the diagonal of a dot product? (★★★) 
(**hint**: np.diag)

In [70]:
Vec1=np.random.randint(0,10,(3,3))
Vec2=np.random.randint(0,10,(3,3))
mat=np.dot(Vec1,Vec2)
np.diag(mat)

array([102,  79, 148])

#### 70. Consider the vector \[1, 2, 3, 4, 5\], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★) 
(**hint**: array\[::4\])

In [71]:
Arry=np.array([1,2,3,4,5])
zer=np.zeros(17)
zer[::4]=Arry
zer.astype(int)

array([1, 0, 0, 0, 2, 0, 0, 0, 3, 0, 0, 0, 4, 0, 0, 0, 5])

#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★) 
(**hint**: array\[:, :, None\])

In [73]:
A = np.ones((5,5,3))
B = 2*np.ones((5,5))
print(A * B[:,:,None])

[[[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]]


#### 72. How to swap two rows of an array? (★★★) 
(**hint**: array\[\[\]\] = array\[\[\]\])

In [74]:
A = np.arange(25).reshape(5,5)
A[[0,1]] = A[[1,0]]
print(A)

[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★) 
(**hint**: repeat, np.roll, np.sort, view, np.unique)

In [75]:
faces = np.random.randint(0,100,(10,3))
F = np.roll(faces.repeat(2,axis=1),-1,axis=1)
F = F.reshape(len(F)*3,2)
F = np.sort(F,axis=1)
G = F.view( dtype=[('p0',F.dtype),('p1',F.dtype)] )
G = np.unique(G)
print(G)

[( 1,  3) ( 1, 45) ( 3, 45) ( 6, 33) ( 6, 68) ( 8, 21) ( 8, 30) (14, 39)
 (14, 79) (17, 62) (17, 80) (17, 88) (18, 63) (18, 78) (21, 30) (25, 74)
 (25, 88) (33, 68) (39, 79) (41, 42) (41, 95) (42, 95) (59, 62) (59, 75)
 (62, 75) (62, 80) (62, 88) (63, 78) (74, 88)]


#### 74. Given an array C that is a bincount, how to produce an array A such that np.bincount(A) == C? (★★★) 
(**hint**: np.repeat)

In [76]:
C = np.bincount([1,1,2,3,4,4,6])
A = np.repeat(np.arange(len(C)), C)
print(A)

[1 1 2 3 4 4 6]


#### 75. How to compute averages using a sliding window over an array? (★★★) 
(**hint**: np.cumsum)

In [77]:
def moving_average(a, n=3) :
    ret = np.cumsum(a, dtype=float)
    ret[n:] = ret[n:] - ret[:-n]
    return ret[n - 1:] / n
Z = np.arange(20)
print(moving_average(Z, n=3))

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.]


#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z\[0\],Z\[1\],Z\[2\]) and each subsequent row is  shifted by 1 (last row should be (Z\[-3\],Z\[-2\],Z\[-1\]) (★★★) 
(**hint**: from numpy.lib import stride_tricks)

In [78]:
from numpy.lib import stride_tricks

def rolling(a, window):
    shape = (a.size - window + 1, window)
    strides = (a.itemsize, a.itemsize)
    return stride_tricks.as_strided(a, shape=shape, strides=strides)
Z = rolling(np.arange(10), 3)
print(Z)

[[0 1 2]
 [1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]
 [5 6 7]
 [6 7 8]
 [7 8 9]]


#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★) 
(**hint**: np.logical_not, np.negative)

In [79]:
Z = np.random.randint(0,2,100)
np.logical_not(Z, out=Z)

Z = np.random.uniform(-1.0,1.0,100)
np.negative(Z, out=Z)

array([-0.77656191, -0.00579307, -0.40586335, -0.54564758,  0.39198316,
        0.25705452,  0.3849587 , -0.86144129, -0.30194723, -0.75827872,
        0.57704033,  0.77752857,  0.73980031, -0.51179956,  0.78526837,
       -0.9857272 ,  0.66972642, -0.22650589, -0.54414552,  0.53085685,
        0.46556771, -0.97386427, -0.45497791,  0.86519303,  0.48531314,
        0.38134367,  0.89856578,  0.15193875,  0.97995248,  0.67921889,
        0.67529176, -0.55111211, -0.85053155,  0.17875879, -0.37489444,
        0.59603226,  0.94917364, -0.09168173, -0.47906392, -0.11201703,
       -0.80088181,  0.91767777,  0.8820768 ,  0.69553602,  0.70056993,
        0.69520603,  0.75205395, -0.02531029,  0.29376732,  0.64516973,
       -0.57466077, -0.12640773, -0.99929186, -0.81545185,  0.67743833,
        0.48365922,  0.79610142, -0.49056703, -0.36771553, -0.72036083,
        0.98108131, -0.26809115, -0.90250889,  0.3890371 ,  0.34710601,
        0.98668572,  0.67356521,  0.09222761,  0.13566724,  0.81

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i  (P0\[i\],P1\[i\])? (★★★)

In [80]:
def distance(P0, P1, p):
    T = P1 - P0
    L = (T**2).sum(axis=1)
    U = -((P0[:,0]-p[...,0])*T[:,0] + (P0[:,1]-p[...,1])*T[:,1]) / L
    U = U.reshape(len(U),1)
    D = P0 + U*T - p
    return np.sqrt((D**2).sum(axis=1))

P0 = np.random.uniform(-10,10,(10,2))
P1 = np.random.uniform(-10,10,(10,2))
p  = np.random.uniform(-10,10,( 1,2))
print(distance(P0, P1, p))

[0.17073198 2.32879153 2.85699581 1.38879625 3.56513098 5.65527104
 7.05352461 4.77904843 7.91279811 3.65370198]


#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P\[j\]) to each line i (P0\[i\],P1\[i\])? (★★★)

In [81]:
P0 = np.random.uniform(-10, 10, (10,2))
P1 = np.random.uniform(-10,10,(10,2))
p = np.random.uniform(-10, 10, (10,2))
print(np.array([distance(P0,P1,p_i) for p_i in p]))

[[10.94148881  5.81531685  5.43782067  4.78926749  3.43990269 10.3560438
   3.60021355  7.54339592  8.31839454  5.31313522]
 [11.10564518  4.48248466  3.41694914  2.24686835  5.89592652  8.94897079
   6.00079021  6.64802508  6.21070898  7.80158126]
 [10.94851353 10.87223914 12.72037661 13.61208709  4.79472201 15.65719555
   4.41147709 11.14731233 15.87322651  3.05539831]
 [ 2.98796759  4.24696772  0.55005752  5.423851    4.1198413   0.6351574
   4.68063698  4.19599291  3.05040863  1.73944678]
 [11.69857412  2.22284882  0.20141334  2.47469944 10.60117002  6.54476325
  10.618305    5.23333322  2.41663924 12.55634983]
 [ 6.62565782  7.29798843 10.21146484 13.02041853  6.4044621  12.16704965
   6.26489794  7.18253452 13.56335726  4.49580039]
 [13.74141047  6.51934909  4.74142887  2.35882398  7.10974308 10.92766237
   7.3569095   8.96400148  7.40613889  8.91591656]
 [14.00038927  5.27594419  2.79147818  0.15134041  9.58309648  9.6087052
   9.78064665  8.16345118  5.36560318 11.41768601]
 [1

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★) 
(**hint**: minimum, maximum)

In [82]:
Z = np.random.randint(0,10,(10,10))
shape = (5,5)
fill  = 0
position = (1,1)

R = np.ones(shape, dtype=Z.dtype)*fill
P  = np.array(list(position)).astype(int)
Rs = np.array(list(R.shape)).astype(int)
Zs = np.array(list(Z.shape)).astype(int)

R_start = np.zeros((len(shape),)).astype(int)
R_stop  = np.array(list(shape)).astype(int)
Z_start = (P-Rs//2)
Z_stop  = (P+Rs//2)+Rs%2

R_start = (R_start - np.minimum(Z_start,0)).tolist()
Z_start = (np.maximum(Z_start,0)).tolist()
R_stop = np.maximum(R_start, (R_stop - np.maximum(Z_stop-Zs,0))).tolist()
Z_stop = (np.minimum(Z_stop,Zs)).tolist()

r = [slice(start,stop) for start,stop in zip(R_start,R_stop)]
z = [slice(start,stop) for start,stop in zip(Z_start,Z_stop)]
R[r] = Z[z]
print(Z)
print(R)

[[2 6 0 7 3 7 7 7 7 1]
 [3 9 1 0 9 5 3 2 1 3]
 [0 5 0 0 0 9 8 0 9 2]
 [1 0 1 0 5 4 3 9 3 8]
 [5 0 1 3 4 8 3 2 0 4]
 [8 9 3 3 1 2 7 1 7 0]
 [6 0 8 8 7 2 1 3 9 5]
 [2 9 2 3 9 4 2 1 9 6]
 [5 5 0 4 1 4 5 7 0 6]
 [3 9 0 8 1 2 3 4 0 7]]
[[0 0 0 0 0]
 [0 2 6 0 7]
 [0 3 9 1 0]
 [0 0 5 0 0]
 [0 1 0 1 0]]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:23: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.


#### 81. Consider an array Z = \[1,2,3,4,5,6,7,8,9,10,11,12,13,14\], how to generate an array R = \[\[1,2,3,4\], \[2,3,4,5\], \[3,4,5,6\], ..., \[11,12,13,14\]\]? (★★★) 
(**hint**: stride\_tricks.as\_strided)

In [83]:
Z = np.arange(1,15,dtype=np.uint32)
R = stride_tricks.as_strided(Z,(11,4),(4,4))
print(R)

[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]


#### 82. Compute a matrix rank (★★★) 
(**hint**: np.linalg.svd) (suggestion: np.linalg.svd)

In [84]:
Z = np.random.uniform(0,1,(10,10))
U, S, V = np.linalg.svd(Z) # Singular Value Decomposition
rank = np.sum(S > 1e-10)
print(rank)

10


#### 83. How to find the most frequent value in an array? 
(**hint**: np.bincount, argmax)

In [85]:
Z = np.random.randint(0,10,50)
print(np.bincount(Z).argmax())

2


#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★) 
(**hint**: stride\_tricks.as\_strided)

In [86]:
Z = np.random.randint(0,5,(10,10))
n = 3
i = 1 + (Z.shape[0]-3)
j = 1 + (Z.shape[1]-3)
C = stride_tricks.as_strided(Z, shape=(i, j, n, n), strides=Z.strides + Z.strides)
print(C)

[[[[2 4 3]
   [0 1 0]
   [2 3 1]]

  [[4 3 2]
   [1 0 3]
   [3 1 0]]

  [[3 2 3]
   [0 3 1]
   [1 0 4]]

  [[2 3 3]
   [3 1 4]
   [0 4 2]]

  [[3 3 1]
   [1 4 1]
   [4 2 3]]

  [[3 1 3]
   [4 1 3]
   [2 3 4]]

  [[1 3 3]
   [1 3 0]
   [3 4 3]]

  [[3 3 3]
   [3 0 4]
   [4 3 3]]]


 [[[0 1 0]
   [2 3 1]
   [4 1 2]]

  [[1 0 3]
   [3 1 0]
   [1 2 0]]

  [[0 3 1]
   [1 0 4]
   [2 0 2]]

  [[3 1 4]
   [0 4 2]
   [0 2 4]]

  [[1 4 1]
   [4 2 3]
   [2 4 3]]

  [[4 1 3]
   [2 3 4]
   [4 3 1]]

  [[1 3 0]
   [3 4 3]
   [3 1 3]]

  [[3 0 4]
   [4 3 3]
   [1 3 3]]]


 [[[2 3 1]
   [4 1 2]
   [4 3 4]]

  [[3 1 0]
   [1 2 0]
   [3 4 3]]

  [[1 0 4]
   [2 0 2]
   [4 3 0]]

  [[0 4 2]
   [0 2 4]
   [3 0 0]]

  [[4 2 3]
   [2 4 3]
   [0 0 3]]

  [[2 3 4]
   [4 3 1]
   [0 3 2]]

  [[3 4 3]
   [3 1 3]
   [3 2 3]]

  [[4 3 3]
   [1 3 3]
   [2 3 2]]]


 [[[4 1 2]
   [4 3 4]
   [3 3 3]]

  [[1 2 0]
   [3 4 3]
   [3 3 3]]

  [[2 0 2]
   [4 3 0]
   [3 3 0]]

  [[0 2 4]
   [3 0 0]
   [3 0 3]]

  [[2 4 3]
   

#### 85. Create a 2D array subclass such that Z\[i,j\] == Z\[j,i\] (★★★) 
(**hint**: class method)

In [87]:
class Symetric(np.ndarray):
    def __setitem__(self, index, value):
        i,j = index
        super(Symetric, self).__setitem__((i,j), value)
        super(Symetric, self).__setitem__((j,i), value)

def symetric(Z):
    return np.asarray(Z + Z.T - np.diag(Z.diagonal())).view(Symetric)

S = symetric(np.random.randint(0,10,(5,5)))
S[2,3] = 42
print(S)

[[ 7  9  7 11 10]
 [ 9  3 15  7 12]
 [ 7 15  5 42  5]
 [11  7 42  8  9]
 [10 12  5  9  6]]


#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★) 
(**hint**: np.tensordot)

In [88]:
p, n = 10, 20
M = np.ones((p,n,n))
V = np.ones((p,n,1))
S = np.tensordot(M, V, axes=[[0, 2], [0, 1]])
print(S)

[[200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]]


#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★) 
(**hint**: np.add.reduceat)

In [89]:
Z = np.ones((16,16))
k = 4
S = np.add.reduceat(np.add.reduceat(Z, np.arange(0, Z.shape[0], k), axis=0),
                                       np.arange(0, Z.shape[1], k), axis=1)
print(S)

[[16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]]


#### 88. How to implement the Game of Life using numpy arrays? (★★★)

In [90]:
def iterate(Z):
    # Count neighbours
    N = (Z[0:-2,0:-2] + Z[0:-2,1:-1] + Z[0:-2,2:] +
         Z[1:-1,0:-2]                + Z[1:-1,2:] +
         Z[2:  ,0:-2] + Z[2:  ,1:-1] + Z[2:  ,2:])

    # Apply rules
    birth = (N==3) & (Z[1:-1,1:-1]==0)
    survive = ((N==2) | (N==3)) & (Z[1:-1,1:-1]==1)
    Z[...] = 0
    Z[1:-1,1:-1][birth | survive] = 1
    return Z

Z = np.random.randint(0,2,(50,50))
for i in range(100): Z = iterate(Z)
print(Z)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


#### 89. How to get the n largest values of an array (★★★) 
(**hint**: np.argsort | np.argpartition)

In [91]:
Z = np.arange(10000)
np.random.shuffle(Z)
n = 5

# Slow
print (Z[np.argsort(Z)[-n:]])

# Fast
print (Z[np.argpartition(-Z,n)[:n]])

[9995 9996 9997 9998 9999]
[9998 9997 9999 9996 9995]


#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★) 
(**hint**: np.indices)

In [92]:
def cartesian(arrays):
    arrays = [np.asarray(a) for a in arrays]
    shape = (len(x) for x in arrays)

    ix = np.indices(shape, dtype=int)
    ix = ix.reshape(len(arrays), -1).T

    for n, arr in enumerate(arrays):
        ix[:, n] = arrays[n][ix[:, n]]

    return ix

print (cartesian(([1, 2, 3], [4, 5], [6, 7])))

[[1 4 6]
 [1 4 7]
 [1 5 6]
 [1 5 7]
 [2 4 6]
 [2 4 7]
 [2 5 6]
 [2 5 7]
 [3 4 6]
 [3 4 7]
 [3 5 6]
 [3 5 7]]


#### 91. How to create a record array from a regular array? (★★★) 
(**hint**: np.core.records.fromarrays)

In [93]:
Z = np.array([("Hello", 2.5, 3),
              ("World", 3.6, 2)])
R = np.core.records.fromarrays(Z.T, 
                               names='col1, col2, col3',
                               formats = 'S8, f8, i8')
print(R)

[(b'Hello', 2.5, 3) (b'World', 3.6, 2)]


#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★) 
(**hint**: np.power, \*, np.einsum)

In [102]:
x = np.random.rand(5*10**7)

print(np.power(x,3))
print(x*x*x)
print(np.einsum('i,i,i->i',x,x,x))

[0.36812243 0.93857275 0.60187376 ... 0.00486691 0.03044518 0.51723324]
[0.36812243 0.93857275 0.60187376 ... 0.00486691 0.03044518 0.51723324]
[0.36812243 0.93857275 0.60187376 ... 0.00486691 0.03044518 0.51723324]


#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★) 
(**hint**: np.where)

In [103]:
A = np.random.randint(0,5,(8,3))
B = np.random.randint(0,5,(2,2))

C = (A[..., np.newaxis, np.newaxis] == B)
rows = np.where(C.any((3,1)).all(1))[0]
print(rows)

[1 4 5 6 7]


#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. \[2,2,3\]) (★★★)

In [104]:
Z = np.random.randint(0,5,(10,3))
print(Z)
# solution for arrays of all dtypes (including string arrays and record arrays)
E = np.all(Z[:,1:] == Z[:,:-1], axis=1)
U = Z[~E]
print(U)
# soluiton for numerical arrays only, will work for any number of columns in Z
U = Z[Z.max(axis=1) != Z.min(axis=1),:]
print(U)

[[3 2 0]
 [4 1 1]
 [1 3 1]
 [2 3 3]
 [2 4 0]
 [4 1 3]
 [4 1 3]
 [3 3 0]
 [1 3 0]
 [1 4 1]]
[[3 2 0]
 [4 1 1]
 [1 3 1]
 [2 3 3]
 [2 4 0]
 [4 1 3]
 [4 1 3]
 [3 3 0]
 [1 3 0]
 [1 4 1]]
[[3 2 0]
 [4 1 1]
 [1 3 1]
 [2 3 3]
 [2 4 0]
 [4 1 3]
 [4 1 3]
 [3 3 0]
 [1 3 0]
 [1 4 1]]


#### 95. Convert a vector of ints into a matrix binary representation (★★★) 
(**hint**: np.unpackbits)

In [105]:
I = np.array([0, 1, 2, 3, 15, 16, 32, 64, 128])
B = ((I.reshape(-1,1) & (2**np.arange(8))) != 0).astype(int)
print(B[:,::-1])

# Author: Daniel T. McDonald

I = np.array([0, 1, 2, 3, 15, 16, 32, 64, 128], dtype=np.uint8)
print(np.unpackbits(I[:, np.newaxis], axis=1))

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 1 1 1 1]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]]
[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 1 1 1 1]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]]


#### 96. Given a two dimensional array, how to extract unique rows? (★★★) 
(**hint**: np.ascontiguousarray)

In [106]:
Z = np.random.randint(0,2,(6,3))
T = np.ascontiguousarray(Z).view(np.dtype((np.void, Z.dtype.itemsize * Z.shape[1])))
_, idx = np.unique(T, return_index=True)
uZ = Z[idx]
print(uZ)

# Author: Andreas Kouzelis
# NumPy >= 1.13
uZ = np.unique(Z, axis=0)
print(uZ)

[[0 0 0]
 [0 1 1]
 [1 0 1]
 [1 1 1]]
[[0 0 0]
 [0 1 1]
 [1 0 1]
 [1 1 1]]


#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★) 
(**hint**: np.einsum)

In [107]:
A = np.random.uniform(0,1,10)
B = np.random.uniform(0,1,10)

np.einsum('i->', A)       # np.sum(A)
np.einsum('i,i->i', A, B) # A * B
np.einsum('i,i', A, B)    # np.inner(A, B)
np.einsum('i,j->ij', A, B)    # np.outer(A, B)

array([[4.63060904e-01, 5.56839591e-01, 5.73907312e-01, 2.51513619e-01,
        5.65553902e-02, 6.55823719e-03, 5.67141579e-02, 3.87690807e-01,
        4.25376465e-01, 5.45189023e-01],
       [3.51781446e-01, 4.23023915e-01, 4.35990044e-01, 1.91071680e-01,
        4.29644066e-02, 4.98220891e-03, 4.30850204e-02, 2.94523747e-01,
        3.23153059e-01, 4.14173127e-01],
       [2.95746345e-01, 3.55640635e-01, 3.66541395e-01, 1.60635962e-01,
        3.61206265e-02, 4.18859520e-03, 3.62220277e-02, 2.47609198e-01,
        2.71678161e-01, 3.48199685e-01],
       [1.25642173e-01, 1.51087116e-01, 1.55718095e-01, 6.82431133e-02,
        1.53451567e-02, 1.77944449e-03, 1.53882351e-02, 1.05192028e-01,
        1.15417266e-01, 1.47925971e-01],
       [3.00269372e-01, 3.61079661e-01, 3.72147133e-01, 1.63092664e-01,
        3.66730409e-02, 4.25265390e-03, 3.67759930e-02, 2.51396035e-01,
        2.75833098e-01, 3.53524912e-01],
       [3.75994739e-01, 4.52140862e-01, 4.65999456e-01, 2.04223239e-01,
   

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)? 
(**hint**: np.cumsum, np.interp)

In [108]:
phi = np.arange(0, 10*np.pi, 0.1)
a = 1
x = a*phi*np.cos(phi)
y = a*phi*np.sin(phi)

dr = (np.diff(x)**2 + np.diff(y)**2)**.5 # segment lengths
r = np.zeros_like(x)
r[1:] = np.cumsum(dr)                # integrate path
r_int = np.linspace(0, r.max(), 200) # regular spaced path
x_int = np.interp(r_int, r, x)       # integrate path
y_int = np.interp(r_int, r, y)

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★) 
(**hint**: np.logical\_and.reduce, np.mod)

In [109]:
X = np.asarray([[1.0, 0.0, 3.0, 8.0],
                [2.0, 0.0, 1.0, 1.0],
                [1.5, 2.5, 1.0, 0.0]])
n = 4
M = np.logical_and.reduce(np.mod(X, 1) == 0, axis=-1)
M &= (X.sum(axis=-1) == n)
print(X[M])

[[2. 0. 1. 1.]]


#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★) 
(**hint**: np.percentile)

In [110]:
X = np.random.randn(100) # random 1D array
N = 1000 # number of bootstrap samples
idx = np.random.randint(0, X.size, (N, X.size))
means = X[idx].mean(axis=1)
confint = np.percentile(means, [2.5, 97.5])
print(confint)

[0.01665447 0.31960698]
